import Head from 'next/head'
import Header from '../components/Header'
import { Breadcrumb, List } from 'antd'
import ReactMarkdown from "react-markdown"
import remarkGfm from 'remark-gfm'
import React, {useState} from "react" 
import axios from 'axios'


function Detailed(content) {
  const [context, setContext] = useState(content)
  console.log(context)
  const md = `00`
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bread-div">
          <Breadcrumb>
            <Breadcrumb.Item><a href="/">首页</a></Breadcrumb.Item>
            <Breadcrumb.Item>视频列表</Breadcrumb.Item>
          </Breadcrumb>
      </div>
      <main>
        <Header />
        <ReactMarkdown children={md} remarkPlugins={[remarkGfm]} />
        <div>
          {context.article_content}
        </div>
      </main>
    </div>
  )
}

Detailed.getInitialProps = async (context)=>{
  console.log(context.query.id)

  let id = context.query.id

  const promise = new Promise((resolve)=>{
    axios('http://127.0.0.1:7001/default/getArticleById' + id).then(
      (res)=>{
        resolve(res.data.data[0])
      }
    )
  })

  return await promise
}

export default Detailed