import Head from 'next/head'
import Header from '../components/Header'
import { Breadcrumb, List } from 'antd'
import ReactMarkdown from "react-markdown"
import remarkGfm from 'remark-gfm'
import React from "react" 
React.useLayoutEffect = React.useEffect 

export default function blogList() {
    const markdown = `A paragraph with *emphasis* and **strong importance**.

> A block quote with ~strikethrough~ and a URL: https://reactjs.org.

* Lists
* [ ] todo
* [x] done

A table:

| a | b |
| - | - |
`
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bread-div">
          <Breadcrumb>
            <Breadcrumb.Item><a href="/">首页</a></Breadcrumb.Item>
            <Breadcrumb.Item>视频列表</Breadcrumb.Item>
          </Breadcrumb>
      </div>
      <main>
        <Header />
        {/* <ReactMarkdown># Hello, *world*!</ReactMarkdown> */}
        <ReactMarkdown children={markdown} remarkPlugins={[remarkGfm]} />
      </main>
    </div>
  )
}
