import { useState } from "react"
import Head from 'next/head'
import Header from '../components/Header'
import { List } from 'antd'
import Link from 'next/link'
import axios from 'axios'

function Home(list) {
  const [blogList, setBlogList] = useState(list.data)
  console.log(blogList)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <Header />
        <List
          header={<div>最新日志</div>}
          itemLayout="vertical"
          dataSource={blogList}
          renderItem={item => (
            <List.Item>
              <div className="blog-title">
                <Link href={{pathname: '/detailed', query: {id:item.id}}}>
                  <a>{item.title}</a>
                </Link>
              </div>
              <div className="blog-context">{item.introduce}</div>
            </List.Item>
          )}
        />
      </main>
    </div>
  )
}

Home.getInitialProps = async ()=>{
  const promise = new Promise((resolve)=>{
    axios('http://127.0.0.1:7001/default/getArticleList').then(
      (res)=>{
        resolve(res.data)
      }
    )
  })

  return await promise
}

export default Home
